[package]
name = "aptos-vfn-check-client"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.62"
aptos-node-checker = { path = "../" }
aptos-sdk = { path = "../../../sdk" }
clap = "3.2.17"
env_logger = "0.9.0"
gcp-bigquery-client = "0.13.0"
log = "0.4.17"
reqwest = "0.11.11"
serde = "1.0.144"
serde_json = "1.0.85"
tokio = { version = "1.18.2", features = ["macros", "rt-multi-thread"] }
url = "2.2.2"
